# test

In [58]:
data = [("soccer footbal player",1),
        ("soccer gate",1),
        ("soccer shot meter",1),
        ("hockey ball player",0),
        ("ice gate player",0),
]
df = pd.DataFrame(data,columns=['text','y'])
df

text  y
0  soccer footbal player  1
1            soccer gate  1
2      soccer shot meter  1
3     hockey ball player  0
4        ice gate player  0

In [59]:
test = ["soccer player"]

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse import csr_matrix

vec = CountVectorizer()

In [61]:
X = vec.fit_transform(df['text'])
y = df['y']
X

<5x9 sparse matrix of type '<class 'numpy.int64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [62]:
x_test = vec.transform(test)
x_test

<1x9 sparse matrix of type '<class 'numpy.int64'>'
	with 2 stored elements in Compressed Sparse Row format>

In [63]:
df_pos = csr_matrix((1, X.shape[1]))
df_neg = csr_matrix((1, X.shape[1]))

In [64]:
for x_i, y_i in zip(X, y):

    if y_i == 0:
        df_neg += x_i
    elif y_i == 1:
        df_pos += x_i

In [65]:
df_neg.toarray()

array([[1., 0., 1., 1., 1., 0., 2., 0., 0.]])

In [66]:
df_pos.toarray()

array([[0., 1., 1., 0., 0., 1., 1., 1., 3.]])

In [80]:
df_pos[0].data

array([1., 1., 3., 1., 1., 1.])

In [81]:
_pos = df_pos - df_neg
_neg = df_neg - df_pos

In [82]:
_pos.toarray()

array([[-1.,  1.,  0., -1., -1.,  1., -1.,  1.,  3.]])

In [83]:
_neg.toarray()

array([[ 1., -1.,  0.,  1.,  1., -1.,  1., -1., -3.]])

In [84]:
x_test[0].multiply(_pos).sum()

2.0

In [86]:
x_test[0].multiply(_neg).sum()

-2.0

In [ ]:
Name: y_pred, dtype: int64
[[282  37]
 [  9 385]]

In [ ]:
[[253  66]
 [  2 392]]